### PR TITLE
Port simple test examples to Google Test.

### PR DESCRIPTION
**Pull request by cyfdecyf**
My application have lots of short queries and I'm planning to do some performance optimization to this library.

This commit adds client unit tests which copies all examples in `test/simple/main.cpp`.

### CODE REVIEW

**Comment by cyfdecyf** [comment]
Travis-ci config does not install ClickHouse server which makes the unit test fail. Not sure if it's good idea to install ClickHouse server in the test environment.

**Comment by artpaul** [comment]
I think that install ClickHouse inside travis-ci test environment it is OK.

**Comment by cyfdecyf** [comment]
Fixed travis ci. Client unittest will only run on Linux.

**Comment by artpaul** [comment]
Thanks!

**Pull request merged**
